;;; static-blog-test.el --- Tests for static blog -*- lexical-binding: t; -*-

(require 'ert)
(require 'static-blog)

(ert-deftest static-blog-publish-file-generates-static-html ()
  (let* ((source-dir (make-temp-file "static-blog-source" t))
         (source-file (expand-file-name "quiet-page.org" source-dir))
         (static-blog-public-directory (make-temp-file "static-blog-public" t))
         (static-blog-assets-directory (expand-file-name "assets" user-emacs-directory)))
    (with-temp-file source-file
      (insert "#+TITLE: 晚风吹过页面\n")
      (insert "#+DATE: 2026-05-27\n")
      (insert "#+DESCRIPTION: 一篇从任意 Org 文件发布的文章。\n\n")
      (insert "* 晚风吹过页面\n\n")
      (insert "这是一篇示例文章，用来确认 org-mode 可以直接发布到博客静态目录。\n"))
    (static-blog-publish-file source-file t)
     (should (file-exists-p (expand-file-name "index.html" static-blog-public-directory)))
     (should (file-exists-p (expand-file-name "quiet-page.html" static-blog-public-directory)))
     (should (file-exists-p (expand-file-name "assets/blog.css" static-blog-public-directory)))
     (should (file-exists-p (expand-file-name "assets/blog.js" static-blog-public-directory)))
     (should-not (file-exists-p (expand-file-name "quiet-page.org" static-blog-public-directory)))
    (with-temp-buffer
      (insert-file-contents (expand-file-name "index.html" static-blog-public-directory))
      (should (search-forward "晚风吹过页面" nil t)))
    (with-temp-buffer
       (insert-file-contents (expand-file-name "quiet-page.html" static-blog-public-directory))
       (should (search-forward "<link rel=\"stylesheet\" href=\"assets/blog.css\">" nil t))
       (should (search-forward "<script src=\"assets/blog.js\" defer></script>" nil t))
       (should (search-forward "class=\"site-header\"" nil t))
       (should (search-forward "class=\"post-content\"" nil t))
       (should (search-forward "这是一篇示例文章" nil t)))))

(ert-deftest static-blog-publish-source-block-without-htmlize-warning ()
  (let* ((source-dir (make-temp-file "static-blog-source" t))
         (source-file (expand-file-name "code-page.org" source-dir))
         (static-blog-public-directory (make-temp-file "static-blog-public" t))
         (static-blog-assets-directory (expand-file-name "assets" user-emacs-directory))
         (warnings nil))
    (with-temp-file source-file
      (insert "#+TITLE: 代码示例\n\n")
      (insert "#+begin_src emacs-lisp\n")
      (insert "(message \"hello\")\n")
      (insert "#+end_src\n"))
    (cl-letf (((symbol-function 'display-warning)
               (lambda (_type message &optional _level _buffer-name)
                 (push (format "%s" message) warnings))))
      (static-blog-publish-file source-file t))
    (should-not (cl-some (lambda (message)
                           (string-match-p "htmlize" message))
                         warnings))
    (should (file-exists-p (expand-file-name "code-page.html" static-blog-public-directory)))))

(ert-deftest static-blog-publish-removes-cjk-soft-line-break-spaces ()
  (let* ((source-dir (make-temp-file "static-blog-source" t))
         (source-file (expand-file-name "cjk-page.org" source-dir))
         (static-blog-public-directory (make-temp-file "static-blog-public" t))
         (static-blog-assets-directory (expand-file-name "assets" user-emacs-directory)))
    (with-temp-file source-file
      (insert "#+TITLE: 中文软换行\n\n")
      (insert "这是第一行\n")
      (insert "这是第二行\n\n")
      (insert "English line\n")
      (insert "keeps space\n"))
    (static-blog-publish-file source-file t)
    (with-temp-buffer
      (insert-file-contents (expand-file-name "cjk-page.html" static-blog-public-directory))
      (should (search-forward "这是第一行这是第二行" nil t))
      (should-not (search-forward "这是第一行 这是第二行" nil t))
      (should (search-forward "English line" nil t))
      (should (search-forward "keeps space" nil t))
      (should-not (search-forward "English linekeeps space" nil t)))))

(ert-deftest static-blog-publish-delegates-side-toc-to-front-end ()
  (let* ((source-dir (make-temp-file "static-blog-source" t))
         (source-file (expand-file-name "toc-page.org" source-dir))
         (static-blog-public-directory (make-temp-file "static-blog-public" t))
         (static-blog-assets-directory (expand-file-name "assets" user-emacs-directory)))
    (with-temp-file source-file
      (insert "#+TITLE: 目录文章\n\n")
      (insert "* 第一章\n\n正文\n")
      (insert "** 第一节\n\n正文\n")
      (insert "* 第二章\n\n正文\n")
      (insert "** 第二节\n\n正文\n"))
    (static-blog-publish-file source-file t)
     (with-temp-buffer
       (insert-file-contents (expand-file-name "toc-page.html" static-blog-public-directory))
       (should (search-forward "class=\"post-shell\"" nil t))
       (goto-char (point-min))
       (should (search-forward "<script src=\"assets/blog.js\" defer></script>" nil t))
       (should-not (search-forward "class=\"toc-panel\"" nil t))
       (should-not (search-forward "data-blog-toc" nil t))
       (should-not (search-forward "data-toc-level=" nil t))
       (should-not (search-forward "data-blog-toc-script" nil t)))))

(ert-deftest static-blog-index-groups-posts-by-year ()
  (let* ((source-dir (make-temp-file "static-blog-source" t))
         (new-file (expand-file-name "new-page.org" source-dir))
         (old-file (expand-file-name "old-page.org" source-dir))
         (static-blog-public-directory (make-temp-file "static-blog-public" t))
         (static-blog-assets-directory (expand-file-name "assets" user-emacs-directory)))
    (with-temp-file new-file
      (insert "#+TITLE: 新文章\n")
      (insert "#+DATE: [2026-05-27 三 17:42]\n\n正文\n"))
    (with-temp-file old-file
      (insert "#+TITLE: 旧文章\n")
      (insert "#+DATE: 2025-12-03\n\n正文\n"))
    (static-blog-publish-file old-file t)
    (static-blog-publish-file new-file t)
    (with-temp-buffer
      (insert-file-contents (expand-file-name "index.html" static-blog-public-directory))
      (should (search-forward "class=\"post-year\"" nil t))
      (should (search-forward ">2026<" nil t))
      (should (search-forward "class=\"post-list-row\"" nil t))
      (should (search-forward "<time>05-27</time>" nil t))
      (should (search-forward ">2025<" nil t))
      (should (search-forward "<time>12-03</time>" nil t))
      (should-not (search-forward "<time>2026-05-27</time>" nil t)))))

(ert-deftest static-blog-render-index-builds-full-document ()
  (let ((html (static-blog--render-index
               (list (list :url "post.html"
                           :title "文章"
                           :date "2026-05-27"
                           :description nil)))))
    (should (string-match-p "\\`<!doctype html>" html))
    (should (string-match-p "class=\"site-header\"" html))
    (should (string-match-p "class=\"post-archive\"" html))
    (should (string-match-p "class=\"site-footer\"" html))))

(ert-deftest static-blog-publish-binds-export-environment ()
  (let* ((source-dir (make-temp-file "static-blog-source" t))
         (source-file (expand-file-name "env-page.org" source-dir))
         (static-blog-public-directory (make-temp-file "static-blog-public" t))
         (static-blog-assets-directory (expand-file-name "assets" user-emacs-directory))
         (seen-htmlize :unset)
         (seen-tab-width :unset)
         (seen-tab-width-local :unset)
         (seen-org-mode-tab-width :unset)
         (original-org-mode (symbol-function 'org-mode))
         (original-export (symbol-function 'org-export-as)))
    (with-temp-file source-file
      (insert "#+TITLE: 环境测试\n\n正文\n"))
    (let ((org-html-htmlize-output-type 'inline-css)
          (tab-width 4))
      (cl-letf (((symbol-function 'org-mode)
                 (lambda (&rest args)
                    (setq seen-org-mode-tab-width
                          (buffer-local-value 'tab-width (current-buffer)))
                    (apply original-org-mode args)))
                 ((symbol-function 'org-export-as)
                  (lambda (&rest args)
                    (setq seen-htmlize org-html-htmlize-output-type)
                    (setq seen-tab-width
                          (buffer-local-value 'tab-width (current-buffer)))
                    (setq seen-tab-width-local (local-variable-p 'tab-width))
                    (apply original-export args))))
        (static-blog-publish-file source-file t)))
    (should seen-org-mode-tab-width)
    (should (eq seen-htmlize (static-blog--htmlize-output-type)))
    (should seen-tab-width-local)
    (should (= seen-tab-width 8))))

(ert-deftest static-blog-publish-converts-id-links-to-html ()
  (let* ((source-dir (make-temp-file "static-blog-source" t))
         (source-file (expand-file-name "source-page.org" source-dir))
         (target-file (expand-file-name "target-page.org" source-dir))
         (target-id "5b955095-ce5f-493d-b90d-b67b12f7ebd7")
         (static-blog-public-directory (make-temp-file "static-blog-public" t))
         (static-blog-assets-directory (expand-file-name "assets" user-emacs-directory)))
    (with-temp-file target-file
      (insert "#+TITLE: 目标文章\n\n")
      (insert "* 目标文章\n")
      (insert ":PROPERTIES:\n")
      (insert ":ID: " target-id "\n")
      (insert ":END:\n\n")
      (insert "目标正文\n"))
    (with-temp-file source-file
      (insert "#+TITLE: 来源文章\n\n")
      (insert "[[id:" target-id "][目标链接]]\n"))
    (let ((org-id-locations-file (expand-file-name ".org-id-locations" source-dir)))
      (org-id-update-id-locations (list target-file))
      (static-blog-publish-file source-file t))
    (with-temp-buffer
      (insert-file-contents (expand-file-name "source-page.html" static-blog-public-directory))
      (should (search-forward
               (concat "href=\"target-page.html#ID-" target-id "\"")
               nil t)))))

(ert-deftest static-blog-publish-keeps-unresolved-id-links ()
  (let* ((source-dir (make-temp-file "static-blog-source" t))
         (source-file (expand-file-name "source-page.org" source-dir))
         (missing-id (format "00000000-0000-0000-0000-%012x" (random #xffffffffffff)))
         (static-blog-public-directory (make-temp-file "static-blog-public" t))
         (static-blog-assets-directory (expand-file-name "assets" user-emacs-directory))
         (org-id-locations-file (expand-file-name ".org-id-locations" source-dir)))
    (with-temp-file source-file
      (insert "#+TITLE: 来源文章\n\n")
      (insert "[[id:" missing-id "][暂未发布的目标]]\n"))
    (static-blog-publish-file source-file t)
    (with-temp-buffer
      (insert-file-contents (expand-file-name "source-page.html" static-blog-public-directory))
      (should (search-forward "暂未发布的目标" nil t))
      (goto-char (point-min))
      (should (search-forward missing-id nil t)))))

(provide 'static-blog-test)
;;; static-blog-test.el ends here
